[build]
  publish = "."
  command = ""

[[plugins]]
  package = "@netlify/plugin-functions-core"

[functions]
  directory = "netlify/functions"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[build.processing.css]
  minify = true

[build.processing.js]
  minify = true
